image: node:10-alpine

before_script:
  - npm install .

stages:
  - publish

publish:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish
  only:
    - master
